services:
  frontend:
    container_name: taobao-frontend
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - user-service
      - product-service

  user-service:
    container_name: taobao-user-service
    build: ./services/user-service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/userdb

  product-service:
    container_name: taobao-product-service
    build: ./services/product-service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/productdb

  cart-service:
    container_name: taobao-cart-service
    build: ./services/cart-service
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/cartdb

  order-service:
    container_name: taobao-order-service
    build: ./services/order-service
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/orderdb

  payment-service:
    container_name: taobao-payment-service
    build: ./services/payment-service
    ports:
      - "8005:8000"

  inventory-service:
    container_name: taobao-inventory-service
    build: ./services/inventory-service
    ports:
      - "8006:8000"

  postgres:
    container_name: taobao-postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taobao
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
